### ISSUE TITLE
Developer Playground showing an empty page

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#2366] opened 2021-03-13 00:22 UTC
**Describe the bug**
Developer Playground doesn't launch, an empty page is showing. 

**To Reproduce**
- Generate and launch a new Cube.js app
- Navigate to http://localhost:4000

**Expected behavior**
Developer Playground working. Instead, it's an empty page with an error in the console.

**Screenshots**
<img width="491" alt="Screenshot 2021-03-12 at 16 20 39" src="https://user-images.githubusercontent.com/3852894/111011718-2157f680-834f-11eb-924d-c73d51da63d3.png">

**Version:**
`"@cubejs-backend/server": "^0.26.54"`

**Comment by paveltiunov** [comment] 2021-03-13 00:28
Duplicate of #2358

**Closed by paveltiunov** 2021-03-13 00:28 UTC
Labels: bug
