### ISSUE TITLE
Improve rollup matching rules

### ISSUE THREAD

**Issue by ivan-vdovin** [cube-js/cube.js#4038] opened 2022-02-03 18:44 UTC
**Describe the bug**
Cube fails to recognize AggregatedPenalties as an additive measure because it has a quite complicated SQL expression in SQL.

**Schema example**

```
cube(`EnforcementActionsReport`, {
  sql: `SELECT * FROM \`RegHub\`.reg_alerts where \`RegHub\`.reg_alerts.archived=0 and \`RegHub\`.reg_alerts.alertCategory='EA'`,
  refreshKey: {
    every: `1 minute`,
  },
  joins: {
    tenants: {
      relationship: `belongsTo`,
      sql: `TRIM(CONVERT(${CUBE}.\`tenantid\`, CHAR)) = TRIM(CONVERT(${tenants}.tenantId, CHAR))`,
    },
    users: {
      relationship: `belongsTo`,
      sql: `TRIM(CONVERT(${CUBE}.\`owner\`, CHAR)) = TRIM(CONVERT(${users}._id, CHAR))`,
    },
    RegAlertsAgencynames: {
      relationship: `hasMany`,
      sql: `${CUBE}._id = ${RegAlertsAgencynames}._id`,
    },
    RegAlerts: {
      relationship: `hasMany`,
      sql: `${CUBE}._id = ${RegAlerts}._id`,
    },
  },
  measures: {
    count: {
      type: `count`,
      drillMembers: [currency, _id],
    },
    AggregatedPenalties: {
      sql: `COALESCE(${CUBE}.\`info.penaltyAmount.value\` + ${CUBE}.\`info.restitutionAmount.value\`, ${CUBE}.\`info.restitutionAmount.value\`, ${CUBE}.\`info.penaltyAmount.value\` , 0) `,
      type: `sum`,
      format: `currency`,
      meta: {
        sql: `${CUBE}.\`info.penaltyAmount.currency\``,
      },
    },
  },
  segments: {
    filterEnforcementActions: {
      sql: `${CUBE}.\`alertCategory\` = 'EA'`,
    },
  },
  preAggregations: {
    eaRollup: {
      external: true,
      measures: [CUBE.count, CUBE.AggregatedPenalties],
      dimensions: [CUBE.currency],
    },
    eActionsReportRollUp: {
      sqlAlias: `EARollUp`,
      external: true,
      measures: [CUBE.count, CUBE.AggregatedPenalties],
      dimensions: [CUBE.currency, RegAlertsAgencynames.agencyNames],
    },
  },
  dimensions: {
    _id: {
      sql: `_id`,
      type: `string`,
      primaryKey: true,
    },
    effectiveDate: {
      sql: `${CUBE}.\`effectiveDate\``,
      type: `time`,
    },
    currency: {
      sql: `COALESCE(${CUBE}.\`info.penaltyAmount.currency\` , "$")`,
      type: `string`,
    },
    tenantid: {
      sql: `${CUBE}.\`tenantId\``,
      type: `string`,
    },
  },
});

cube(`RegAlertsAgencynames`, {
  sql: `SELECT * FROM \`RegHub\`.\`reg_alerts_agencyNames\``,

  joins: {
    RegHarmonizedActionType: {
      relationship: `hasMany`,
      sql: `${CUBE._id} = ${RegHarmonizedActionType._id}`,
    },
  },

  measures: {
    count: {
      type: `count`,
      drillMembers: [agencyNames, _id],
    },
  },

  preAggregations: {
    agencyRollup: {
      sqlAlias: `aGroll`,
      external: true,
      measures: [CUBE.count],
      dimensions: [CUBE._id, CUBE.agencyNames],
    },
    agencyActionTypeRollUp: {
      sqlAlias: `HAGroll`,
      external: true,
      measures: [CUBE.count],
      dimensions: [
        CUBE.agencyNames,
        RegHarmonizedActionType.harmonizedActionType,
      ],
    },
  },

  dimensions: {
    agencyNames: {
      sql: `${CUBE}.\`agencyNames\``,
      type: `string`,
      title: `agencyNames`,
    },
    _id: {
      sql: `${CUBE}.\`_id\``,
      type: `string`,
      primaryKey: true,
    },
  },

  dataSource: `default`,
});
```

**Additional context**
https://cube-js.slack.com/archives/CC0403RRR/p1642769348139600

**Comment by paveltiunov** [comment] 2022-02-09 03:26
Duplicate of #4055

**Closed by paveltiunov** 2022-02-09 03:26 UTC
Labels: bug
