### ISSUE TITLE
Dimension String Length Limit

### ISSUE THREAD

**Issue by trotha01** [cube-js/cube.js#1410] opened 2020-11-18 16:30 UTC
**Describe the bug**
When using a dimension such as "Dataset_5e8b2af6890202100a6e64f1.f0" in a query works fine, but if we update the cube to have dimension names like "Dataset_5e8b2af6890202100a6e64f1.field_244e6573_264c_41d7_9411_96ca1059bfdd", and try to query it, we get the error:
```
Error: You requested hidden member: 'dataset_5e8b2af6890202100a6e64f1__field_244e6573_264c_41d7_9411'. Please make it visible using `shown: true`. Please note primaryKey fields are `shown: false` by default: https://cube.dev/docs/joins#setting-a-primary-key.
```

It looks like the string is getting truncated, also the dot is converted to an underscore.
The error message is misleading since simply shortening the dimension name will allow the query to work again.

**To Reproduce**
1. Create a cube with a long string name as a dimension.
2. Run a query with that dimension
3. See error

**Expected behavior**
Either longer strings are permitted or an error message is returned specifying the max string length for a dimension.

**Screenshots**

**Version:**
@cubejs-client/core: ^0.19.43

**Additional context**

**Comment by ovr** [comment] 2020-11-25 13:39
Hello @trotha01,

We don't support `sqlAlias` for dimensions (only for pre-aggregations). There are no plans in the current ROADMAP to support it. As a quick solution, I can suggest you change dimensions on your side (yes, I know that it's painful).

Feel free to submit a PR with implementation of `sqlAlias` for dimensions.

Thanks

**Comment by hassankhan** [comment] 2021-05-05 00:46
Closing as duplicate of https://github.com/cube-js/cube.js/issues/1387

**Closed by hassankhan** 2021-05-05 00:46 UTC
Labels: backend:server, enhancement, help wanted
