### ISSUE TITLE
Error The multi-part identifier "fact__X_key__dim__Y.Field" could not be bound.

### ISSUE THREAD

**Issue by roccamassi** [cube-js/cube.js#4199] opened 2022-03-10 08:37 UTC
When i create one complex query, i don t know because cubejs create one query and one another subquery in left join with first query, and after group by clausole is not correct and i receive this particular error.
Shema is:
![image](https://user-images.githubusercontent.com/17701523/157832762-3c318115-e1b2-4355-8eb6-6a887f677f2b.png)
i want to do one Sum of Amount in Fact_TaxMunicipality group by Region where Region is in Dim_location table.
Cubejs generate this query
`exec sp_executesql @statement=N'
SELECT  TOP 10000 "keys"."dim__location__region", 
		sum("fact__tax_municipality_key__fact__tax_municipality"."Amount") "fact__tax_municipality__sum_of_numeric_value" 
FROM (	SELECT DISTINCT	"fact__tax_municipality_key__dim__location"."Region" "dim__location__region", 
						"fact__tax_municipality_key__fact__tax_municipality"."Id" "fact__tax_municipality__id" 
		FROM dbo."Fact_TaxMunicipality" AS "fact__tax_municipality_key__fact__tax_municipality"
		LEFT JOIN dbo."Fact_TaxAgency" AS "fact__tax_municipality_key__fact__tax_agency" ON "fact__tax_municipality_key__fact__tax_municipality".Id = "fact__tax_municipality_key__fact__tax_agency".IdTaxMunicipality
		LEFT JOIN dbo."Dim_Site" AS "fact__tax_municipality_key__dim__site" ON "fact__tax_municipality_key__dim__site".Id = "fact__tax_municipality_key__fact__tax_agency".IdSite
		LEFT JOIN dbo."Dim_Location" AS "fact__tax_municipality_key__dim__location" ON "fact__tax_municipality_key__dim__site".IdLocation = "fact__tax_municipality_key__dim__location".Id
		LEFT JOIN dbo."Dim_DataSegregation" AS "fact__tax_municipality_key__dim__data_segregation" ON "fact__tax_municipality_key__dim__site".Id = "fact__tax_municipality_key__dim__data_segregation".IdSite  
		WHERE (("fact__tax_municipality_key__dim__data_segregation"."IsEnabled" = @_1) and ("fact__tax_municipality_key__dim__data_segregation"."IdCompany" = @_2))) AS "keys"
		LEFT JOIN dbo."Fact_TaxMunicipality" AS "fact__tax_municipality_key__fact__tax_municipality" ON "keys"."fact__tax_municipality__id" = "fact__tax_municipality_key__fact__tax_municipality"."Id"
GROUP BY "fact__tax_municipality_key__dim__location"."Region"  
ORDER BY 2 DESC',@params=N'@_1 int, @_2 nvarchar(36)',@_1=1,@_2=N'c313c514-4152-4328-83a6-2b4afaef7823'`
Error is in Group by because there is "fact__tax_municipality_key__dim__location"."Region"   but is not correct , correct is "keys"."dim__location__region",
And i don t understund because cubejs generate one subquery, if i use another aggregate for example sum, generate a correct query.
Version of CubeJs is 0.29.31

**Comment by paveltiunov** [comment] 2022-03-28 03:56
Hey @roccamassi ! Cube Data schema and query would be really helpful here.

**Comment by roccamassi** [comment] 2022-03-28 06:46
Ciao @paveltiunov , these are a cube in cubejs:

`
cube(`Dim_Campaign`, {
  sql: `SELECT * FROM dbo."Dim_Campaign"`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
  },
  
  measures: {},
  
  dimensions: {
    id: {
      sql: `${CUBE}."Id"`,
      type: `string`,
      primaryKey: true
    },
    
    campaignName: {
      sql: `${CUBE}."CampaignName"`,
      type: `string`
    },
    
    exposureFrom: {
      sql: `${CUBE}."ExposureFrom"`,
      type: `time`
    },
    
    exposureTo: {
      sql: `${CUBE}."ExposureTo"`,
      type: `time`
    },
    
    exposureType: {
      sql: `${CUBE}."ExposureType"`,
      type: `string`
    }
    
  },
  
  dataSource: `default`
});


cube(`Fact_TaxMunicipality`, {
  sql: `SELECT * FROM dbo."Fact_TaxMunicipality"`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
    Dim_Campaign: {
      relationship: `belongsTo`,
      sql: `${Dim_Campaign}.Id = ${CUBE}.IdCampaign`,
    },
    Fact_TaxAgency: {
      relationship: `hasMany`,
      sql: `${CUBE}.Id = ${Fact_TaxAgency}.IdTaxMunicipality`,
    },
  },
  
  measures: {
    count: {
      type: `count`,
      drillMembers: [
        id,
        idCampaign,
        authorityCollectorCode,
        mQ,
        amount,
        rateNumber,
        payedBy,
        paymentCode,
        hasFile,
        additionalAmount,
        assigned
      ],
    }
   /* sumOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `sum`
    },
    avgOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `avg`,
    },
    minOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `min`,
    },
    maxOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `max`,
    }*/
  },
  
  dimensions: {
    id: {
      sql: `${CUBE}."Id"`,
      type: `string`,
      primaryKey: true
    },
    
    idCampaign: {
      sql: `${CUBE}."IdCampaign"`,
      type: `string`
    },
       
    authorityCollectorCode: {
      sql: `${CUBE}."AuthorityCollectorCode"`,
      type: `string`
    },
    
    mQ: {
      sql: `${CUBE}."MQ"`,
      type: `number`
    },
    
    amount: {
      sql: `${CUBE}."Amount"`,
      type: `number`
    },
    
    rateNumber: {
      sql: `${CUBE}."RateNumber"`,
      type: `number`
    },
    
    payedBy: {
      sql: `${CUBE}."PayedBy"`,
      type: `string`
    },
    
    paymentCode: {
      sql: `${CUBE}."PaymentCode"`,
      type: `string`
    },
    
    hasFile: {
      sql: `${CUBE}."HasFile"`,
      type: `boolean`
    },
    
    additionalAmount: {
      sql: `${CUBE}."AdditionalAmount"`,
      type: `number`
    },
    
    assigned: {
      sql: `${CUBE}."Assigned"`,
      type: `boolean`
    }  
  },
  
  dataSource: `default`
});

cube(`Fact_TaxAgency`, {
  sql: `SELECT * FROM dbo."Fact_TaxAgency"`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
    //Fact_TaxMunicipality: {
    //  relationship: `belongsTo`,
    //  sql: `${Fact_TaxMunicipality}.Id = ${CUBE}.IdTaxMunicipality`,
    //},
    Dim_Site: {
      relationship: `belongsTo`,
      sql: `${Dim_Site}.Id = ${CUBE}.IdSite`,
    },
  },
  
  measures: {
    count: {
      type: `count`,
      drillMembers: [
        id,
        idTaxMunicipality,
        mQ,
        payedBy,
        paymentCode,
        hasFile,
        assigned,
        idSite,
        amount
      ],
    }
   /* sumOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `sum`
    },
    avgOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `avg`,
    },
    minOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `min`,
    },
    maxOfNumericValue: {
      sql: `${CUBE}."Amount"`,
      type: `max`,
    }*/
  },
  
  dimensions: {
    id: {
      sql: `${CUBE}."Id"`,
      type: `string`,
      primaryKey: true
    },
    
    idTaxMunicipality: {
      sql: `${CUBE}."IdTaxMunicipality"`,
      type: `string`
    },
    
    idSite: {
      sql: `${CUBE}."IdSite"`,
      type: `number`
    },
    
    mQ: {
      sql: `${CUBE}."MQ"`,
      type: `number`
    },
    
    amount: {
      sql: `${CUBE}."Amount"`,
      type: `number`
    },
    
    assigned: {
      sql: `${CUBE}."Assigned"`,
      type: `boolean`
    },
    
    payedBy: {
      sql: `${CUBE}."PayedBy"`,
      type: `string`
    },
    
    paymentCode: {
      sql: `${CUBE}."PaymentCode"`,
      type: `string`
    },
    
    hasFile: {
      sql: `${CUBE}."HasFile"`,
      type: `boolean`
    },
    
    taxType: {
      sql: `${CUBE}."TaxType"`,
      type: `string`
    }
  },
  
  dataSource: `default`
});

cube(`Dim_Site`, {
  sql: `SELECT * FROM dbo."Dim_Site"`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
    Dim_DataSegregation: {
      relationship: `hasOne`,
      sql: `${CUBE}.Id = ${Dim_DataSegregation}.IdSite`,
    },
    Dim_Location: {
      relationship: `hasOne`,
      sql: `${CUBE}.IdLocation = ${Dim_Location}.Id`,
    },
    //Fact_Project: {
    //  relationship: `hasMany`,
    //  sql: `${CUBE}.Id= ${Fact_Project}.IdSite`,
    //},
    //Fact_Authorization: {
    //  relationship: `hasMany`,
    //  sql: `${CUBE}.Id= ${Fact_Authorization}.IdSite`,
    //},
    //Fact_Cancellation: {
    //  relationship: `hasMany`,
    //  sql: `${CUBE}.Id= ${Fact_Cancellation}.IdSite`,
    //},
    //Fact_Volture: {
    //  relationship: `hasMany`,
    //  sql: `${CUBE}.Id= ${Fact_Volture}.IdSite`,
    //},
    //Dim_Operation: {
    //  relationship: `hasMany`,
    //  sql: `${CUBE}.Id= ${Dim_Operation}.IdSite`,
    //},
  },
  
  measures: {
    count: {
      type: `count`,
      drillMembers: [id, idLocation]
    }
  },
  
  dimensions: {
    id: {
      sql: `${CUBE}."Id"`,
      type: `string`,
      primaryKey: true
    },
    
    idLocation: {
      sql: `${CUBE}."IdLocation"`,
      type: `string`
    },
    
    address: {
      sql: `${CUBE}."Address"`,
      type: `string`
    },
    
    floor: {
      sql: `${CUBE}."Floor"`,
      type: `string`
    },
    
    gen1: {
      sql: `${CUBE}."Gen1"`,
      type: `string`
    },
    
    gen2: {
      sql: `${CUBE}."Gen2"`,
      type: `string`
    },
    
    gen3: {
      sql: `${CUBE}."Gen3"`,
      type: `string`
    },
    
    gen4: {
      sql: `${CUBE}."Gen4"`,
      type: `string`
    },
    
    gen5: {
      sql: `${CUBE}."Gen5"`,
      type: `string`
    },
    
    gen6: {
      sql: `${CUBE}."Gen6"`,
      type: `string`
    },
    
    gen7: {
      sql: `${CUBE}."Gen7"`,
      type: `string`
    },
    
    gen8: {
      sql: `${CUBE}."Gen8"`,
      type: `string`
    },
    
    gen9: {
      sql: `${CUBE}."Gen9"`,
      type: `string`
    },
    
    gen10: {
      sql: `${CUBE}."Gen10"`,
      type: `string`
    },
    
    gen11: {
      sql: `${CUBE}."Gen11"`,
      type: `string`
    },
    
    gen12: {
      sql: `${CUBE}."Gen12"`,
      type: `string`
    },
    
    gen13: {
      sql: `${CUBE}."Gen13"`,
      type: `string`
    },
    
    gen14: {
      sql: `${CUBE}."Gen14"`,
      type: `string`
    },
    
    gen15: {
      sql: `${CUBE}."Gen15"`,
      type: `string`
    },
    
    gen16: {
      sql: `${CUBE}."Gen16"`,
      type: `string`
    },
    
    gen17: {
      sql: `${CUBE}."Gen17"`,
      type: `string`
    },
    
    gen18: {
      sql: `${CUBE}."Gen18"`,
      type: `string`
    },
    
    gen19: {
      sql: `${CUBE}."Gen19"`,
      type: `string`
    },
    
    gen20: {
      sql: `${CUBE}."Gen20"`,
      type: `string`
    },
    
    gen21: {
      sql: `${CUBE}."Gen21"`,
      type: `string`
    },
    
    gen22: {
      sql: `${CUBE}."Gen22"`,
      type: `string`
    },
    
    gen23: {
      sql: `${CUBE}."Gen23"`,
      type: `string`
    },
    
    gen24: {
      sql: `${CUBE}."Gen24"`,
      type: `string`
    },
    
    gen25: {
      sql: `${CUBE}."Gen25"`,
      type: `string`
    },
    
    gen26: {
      sql: `${CUBE}."Gen26"`,
      type: `string`
    },
    
    gen27: {
      sql: `${CUBE}."Gen27"`,
      type: `string`
    },
    
    gen28: {
      sql: `${CUBE}."Gen28"`,
      type: `string`
    },
    
    gen29: {
      sql: `${CUBE}."Gen29"`,
      type: `string`
    },
    
    gen30: {
      sql: `${CUBE}."Gen30"`,
      type: `string`
    },
    
    gen31: {
      sql: `${CUBE}."Gen31"`,
      type: `string`
    },
    
    gen32: {
      sql: `${CUBE}."Gen32"`,
      type: `string`
    },
    
    gen33: {
      sql: `${CUBE}."Gen33"`,
      type: `string`
    },
    
    gen34: {
      sql: `${CUBE}."Gen34"`,
      type: `string`
    },
    
    gen35: {
      sql: `${CUBE}."Gen35"`,
      type: `string`
    },
    
    gen36: {
      sql: `${CUBE}."Gen36"`,
      type: `string`
    },
    
    gen37: {
      sql: `${CUBE}."Gen37"`,
      type: `string`
    },
    
    gen38: {
      sql: `${CUBE}."Gen38"`,
      type: `string`
    },
    
    gen39: {
      sql: `${CUBE}."Gen39"`,
      type: `string`
    },
    
    gen40: {
      sql: `${CUBE}."Gen40"`,
      type: `string`
    },
    
    gen41: {
      sql: `${CUBE}."Gen41"`,
      type: `string`
    },
    
    gen42: {
      sql: `${CUBE}."Gen42"`,
      type: `string`
    },
    
    gen43: {
      sql: `${CUBE}."Gen43"`,
      type: `string`
    },
    
    gen44: {
      sql: `${CUBE}."Gen44"`,
      type: `string`
    },
    
    gen45: {
      sql: `${CUBE}."Gen45"`,
      type: `string`
    },
    
    gen46: {
      sql: `${CUBE}."Gen46"`,
      type: `string`
    },
    
    gen47: {
      sql: `${CUBE}."Gen47"`,
      type: `string`
    },
    
    gen48: {
      sql: `${CUBE}."Gen48"`,
      type: `string`
    },
    
    gen49: {
      sql: `${CUBE}."Gen49"`,
      type: `string`
    },
    
    gen50: {
      sql: `${CUBE}."Gen50"`,
      type: `string`
    },
    
    gen51: {
      sql: `${CUBE}."Gen51"`,
      type: `string`
    },
    
    gen52: {
      sql: `${CUBE}."Gen52"`,
      type: `string`
    },
    
    gen53: {
      sql: `${CUBE}."Gen53"`,
      type: `string`
    },
    
    gen54: {
      sql: `${CUBE}."Gen54"`,
      type: `string`
    },
    
    gen55: {
      sql: `${CUBE}."Gen55"`,
      type: `string`
    },
    
    gen56: {
      sql: `${CUBE}."Gen56"`,
      type: `string`
    },
    
    gen57: {
      sql: `${CUBE}."Gen57"`,
      type: `string`
    },
    
    gen58: {
      sql: `${CUBE}."Gen58"`,
      type: `string`
    },
    
    gen59: {
      sql: `${CUBE}."Gen59"`,
      type: `string`
    },
    
    gen60: {
      sql: `${CUBE}."Gen60"`,
      type: `string`
    },
    
     gen61: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen62: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen63: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen64: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen65: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen66: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen67: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen68: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen69: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen70: {
      sql: `${CUBE}."Gen61"`,
      type: `number`,
    },

    gen71: {
      sql: `${CUBE}."Gen71"`,
      type: `boolean`
    },
    
    gen72: {
      sql: `${CUBE}."Gen72"`,
      type: `boolean`
    },
    
    gen73: {
      sql: `${CUBE}."Gen73"`,
      type: `boolean`
    },
    
    gen74: {
      sql: `${CUBE}."Gen74"`,
      type: `boolean`
    },
    
    gen75: {
      sql: `${CUBE}."Gen75"`,
      type: `boolean`
    },
    
    gen76: {
      sql: `${CUBE}."Gen76"`,
      type: `boolean`
    },
    
    gen77: {
      sql: `${CUBE}."Gen77"`,
      type: `boolean`
    },
    
    gen78: {
      sql: `${CUBE}."Gen78"`,
      type: `boolean`
    },
    
    gen79: {
      sql: `${CUBE}."Gen79"`,
      type: `boolean`
    },
    
    gen80: {
      sql: `${CUBE}."Gen80"`,
      type: `boolean`
    },
    
    gen81: {
      sql: `${CUBE}."Gen81"`,
      type: `time`
    },
    
    gen82: {
      sql: `${CUBE}."Gen82"`,
      type: `time`
    },
    
    gen83: {
      sql: `${CUBE}."Gen83"`,
      type: `time`
    },
    
    gen84: {
      sql: `${CUBE}."Gen84"`,
      type: `time`
    },
    
    gen85: {
      sql: `${CUBE}."Gen85"`,
      type: `time`
    },
    
    gen86: {
      sql: `${CUBE}."Gen86"`,
      type: `time`
    },
    
    gen87: {
      sql: `${CUBE}."Gen87"`,
      type: `time`
    },
    
    gen88: {
      sql: `${CUBE}."Gen88"`,
      type: `time`
    },
    
    gen89: {
      sql: `${CUBE}."Gen89"`,
      type: `time`
    },
    
    gen90: {
      sql: `${CUBE}."Gen90"`,
      type: `time`
    }
  },
  
  dataSource: `default`
});

cube(`Dim_Location`, {
  sql: `SELECT * FROM dbo."Dim_Location"`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
    // Dim_Site: {
    //   relationship: `hasMany`,
    //   sql: `${CUBE}.Id = Dim_Site.IdLocation` 
    // }
  },
  
  measures: {
    count: {
      type: `count`,
      drillMembers: [id, state, region, province, municipality, city]
    }
  },
  
  dimensions: {
    id: {
      sql: `${CUBE}."Id"`,
      type: `string`,
      primaryKey: true
    },
    
    state: {
      sql: `${CUBE}."State"`,
      type: `string`
    },
    
    stateCode: {
      sql: `${CUBE}."StateCode"`,
      type: `string`
    },
    
    region: {
      sql: `${CUBE}."Region"`,
      type: `string`
    },
    
    regionCode: {
      sql: `${CUBE}."RegionCode"`,
      type: `string`
    },
    
    province: {
      sql: `${CUBE}."Province"`,
      type: `string`
    },
    
    provinceCode: {
      sql: `${CUBE}."ProvinceCode"`,
      type: `string`
    },
    
    municipality: {
      sql: `${CUBE}."Municipality"`,
      type: `string`
    },
    
    municipalityCode: {
      sql: `${CUBE}."MunicipalityCode"`,
      type: `string`
    },
    
    city: {
      sql: `${CUBE}."City"`,
      type: `string`
    },
    
    postalCode: {
      sql: `${CUBE}."PostalCode"`,
      type: `string`
    }
  },
  
  dataSource: `default`
});

cube(`Dim_DataSegregation`, {
  sql: `SELECT * FROM dbo."Dim_DataSegregation"`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
    Dim_Customer: {
      relationship: `belongsTo`,
      sql: `${CUBE}.IdCustomer = ${Dim_Customer}.Id`,
    },
    Dim_Company: {
      relationship: `belongsTo`,
      sql: `${CUBE}.IdCompany = ${Dim_Company}.Id`,
    },
    Dim_Site: {
      relationship: `hasOne`,
      sql: `${CUBE}.IdSite = ${Dim_Site}.Id`,
    }
  },
  
  measures: {},
  
  dimensions: {
    id: {
      sql: `${CUBE}."Id"`,
      type: `string`,
      primaryKey: true
    },
    
    idCustomer: {
      sql: `${CUBE}."IdCustomer"`,
      type: `string`
    },
    
    idCompany: {
      sql: `${CUBE}."IdCompany"`,
      type: `string`
    },
    
    idCompanyApp: {
      sql: `${CUBE}."IdCompanyApp"`,
      type: `string`
    },
    
    companyApp: {
      sql: `${CUBE}."CompanyApp"`,
      type: `string`
    },
    
    idSite: {
      sql: `${CUBE}."IdSite"`,
      type: `string`
    },
    
    siteCode: {
      sql: `${CUBE}."SiteCode"`,
      type: `string`
    },
    
    siteBusinessName: {
      sql: `${CUBE}."SiteBusinessName"`,
      type: `string`
    },
    
    siteCategory: {
      sql: `${CUBE}."SiteCategory"`,
      type: `string`
    },
    
    isEnabled: {
      sql: `${CUBE}."IsEnabled"`,
      type: `boolean`
    }
  },
  
  dataSource: `default`
});

`

**Comment by paveltiunov** [comment] 2022-06-26 17:13
This is duplicate of #573

**Closed by paveltiunov** 2022-06-26 17:13 UTC
Labels: question
