### ISSUE TITLE
Clickhouse adapter hardcodes start of week to Monday when the "week" granularity is specified for a time dimension

### ISSUE THREAD

**Issue by nayakravi** [cube-js/cube.js#4971] opened 2022-07-21 14:53 UTC
Currently, when you compose a query such as the following on a cube over a Clickhouse database:
```
{
  "limit": 10,
  "timeDimensions": [
    {
      "dimension": "MyCube.created",
      "dateRange": [
        "2021-06-30",
        "2022-06-30"
      ],
      "granularity": "week"
    }
  ],
  "order": {
    "MyCube.created": "asc"
  },
  "measures": [
    "MyCube.count"
  ],
  "filters": [
    {
      "member": "MyCube.accountId",
      "operator": "equals",
      "values": [
        "1234567890"
      ],
      "timezone": "America/New_York"
    }
  ]
}
```

It generates a SQL Query of the form:

```
SELECT
  toDateTime(toMonday(toTimeZone(toDateTime(`pm`.created), 'America/New_York'), 'America/New_York'), 'America/New_York') 
  `pm__created_week`, count(*) `pm__count`
FROM
  (
    ....
  ) AS `pm`
WHERE (`pm`.created >= parseDateTimeBestEffort(?) AND `pm`.created <= parseDateTimeBestEffort(?))
AND (`pm`.account_id = ?)
GROUP BY `pm__created_week`
ORDER BY `pm__created_week`
ASC LIMIT 10
```
Notice the `toMonday` function in the query. This is hardcoded [here](https://github.com/cube-js/cube.js/blob/d7255d754350d433b3efdf568ae20f324f577d3d/packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.js#L53).

Ideally this should be locale sensitive since the first day of the week is part of the locale. See https://momentjs.com/docs/#/get-set/weekday/ as an example of how momentjs provides a locale aware way to retrieve the first day of week. They also provide an isoWeekday function that always starts on a Monday. Since we are based in the US and most calendars here have the week starting on a Sunday, we want to change this query accordingly.
Since making this locale sensitive is a larger feature in cube (since it will need an API change to pass in locale information via the query and then implementations in all databases), we would at least like to make this configurable in the adapter in the short term.
Clickhouse provides a [toStartOfWeek function](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#tostartofweektmode) that takes a mode parameter - a value of 0 uses Sunday as the first day of the week and 1 uses Monday as the first day of the week. So, if we can somehow configure this mode parameter on the server, we can solve this issue.

I can create a PR for this, if you guys provide some guidance on the best way to configure this. I was thinking of using an environment variable on the server to configure this for now. Please let me know if this works.

**Comment by paveltiunov** [comment] 2022-07-21 21:42
@nayakravi I guess it's a duplicate of #177. I believe we just need to support `sundayWeek` granularity here.

**Closed by paveltiunov** 2022-07-21 21:42 UTC
