### ISSUE TITLE
Enable prometheus metrics export support with config

### ISSUE THREAD

**Issue by svdimchenko** [cube-js/cube.js#6130] opened 2023-02-07 17:41 UTC
According to https://cube.dev/docs/configuration/extending-cubejs we need to build extra docker image with express-prometheus-middleware installed. It would be nice to have possibility to enable it with some kind of config.

**Comment by paveltiunov** [comment] 2023-02-12 20:32
Duplicate of #2920

**Closed by paveltiunov** 2023-02-12 20:32 UTC
Labels: duplicate
