### ISSUE TITLE
need Language support 

### ISSUE THREAD

**Issue by ChanJeff123** [cube-js/cube.js#1674] opened 2020-12-23 09:56 UTC
when I change schema file  ,
I get a error 
Error: Error: Compile errors: 游戏 cube: child "name" fails because ["name" with value "游戏" fails to match the identifier pattern]

help someone can fix that,or i can join to help

**Comment by ovr** [comment] 2020-12-23 11:34
Hello @ChanJeff123 ,

You can use `title` to set display name for cubes.

https://cube.dev/docs/cube#parameters-title

Thanks

**Comment by paveltiunov** [comment] 2020-12-23 19:56
This is a duplicate of #1360

**Closed by paveltiunov** 2020-12-23 19:56 UTC
Labels: question
