### ISSUE TITLE
Does cubejs support nested filters with and/or logic inside?

### ISSUE THREAD

**Issue by mrksoftware** [cube-js/cube.js#4201] opened 2022-03-10 17:22 UTC
**Problem**

Apparently, it is not possible to have such filter as described in this section of the docs: [Boolean logical operators](https://cube.dev/docs/query-format#boolean-logical-operators)
If we try to do that, on `Vue`, the result returned by the `query-builder` component totally delete the nested `and` section

**Object passed to the `setFilters` method**
```javascript
{
   "or":[
      {
         "and":[
            {
               "operator":"contains",
               "member":"Fact_Project.protocol",
               "values":[
                  "2021"
               ]
            },
            {
               "operator":"contains",
               "member":"Dim_Commission.name",
               "values":[
                  "commission"
               ]
            }
         ]
      },
      {
         "operator":"notContains",
         "member":"Fact_Project.protocol",
         "values":[
            "2022"
         ]
      }
   ]
}
```
As you can see, the structure of this, is exactly as in the example from the docs

**Related Cube.js generated SQL**

```sql
SELECT TOP 10000
          "fact__project"."Protocol" "fact__project__protocol",
          "dim__commission"."Name" "dim__commission__name",
          Count("fact__authorization"."Id") "fact__authorization__count",
          Count("fact__project"."Id") "fact__project__count"
FROM      dbo."Fact_Authorization" AS "fact__authorization"
LEFT JOIN dbo."Fact_Project"       AS "fact__project"
ON        "fact__authorization".idproject = "fact__project".id
LEFT JOIN dbo."Dim_Commission" AS "dim__commission"
ON        "dim__commission".id = "fact__authorization".idcommission
LEFT JOIN dbo."Dim_Site" AS "dim__site"
ON        "dim__site".id = "fact__authorization".idsite
LEFT JOIN dbo."Dim_DataSegregation" AS "dim__data_segregation"
ON        "dim__site".id = "dim__data_segregation".idsite
WHERE     ((
                              Lower("fact__project"."Protocol") NOT LIKE Concat(''%'', Lower(@_1) ,''%'')
                    OR        "fact__project"."Protocol" IS NULL))
AND       ((
                              "dim__data_segregation"."IsEnabled" = @_2)
          AND       (
                              "dim__data_segregation"."IdCustomer" = @_3))
GROUP BY  "fact__project"."Protocol",
          "dim__commission"."Name"
ORDER BY  3 DESC'

@params=N'@_1 nvarchar(4),
          @_2 int,
          @_3 nvarchar(36)',

@_1=N'2022',
@_2=1,
@_3=N'idcustomer'
```

As you can see, in the generated sql, we have just one parameter `@_1` but we totally lost parameter values `2021`, `commission`
It appears that the code inside `cubejs-client-vue.js` doesn't support nested levels of `or`, `and` operator.. I tried to take a look and debug `setMembers` method, and what happens is that:

We call this line of code, cause we have an `or` at the top level
![image](https://user-images.githubusercontent.com/7292153/157717466-442d64fb-add2-46a1-a900-c361bc21631a.png)
but `resolveMembers` doesn't check if and `and` | `or` operator are in any nested level.. I expected to find some sort of recursive pattern inside

Also, by inspecting `query-builder` in `vue-dev-tools` this is what the vizStateChange event returns to us:

![image](https://user-images.githubusercontent.com/7292153/157718415-1bf1c3e4-0629-42d3-b193-f7d1f95efe35.png)

And this is what the `query` parameter from `query-builder` looks like:

![image](https://user-images.githubusercontent.com/7292153/157718532-dfac9eaf-4e2f-4625-9e2c-a16be7158ee5.png)

The section about the inner and, is totally gone!

Am I losing something or this kind of filters are not supported yet?

**Comment by ThomasKientz** [comment] 2022-04-20 09:46
Currently the Vue QueryBuilder components doesn't support nested boolean logical operators. I have submited a PR https://github.com/cube-js/cube.js/pull/4314 to fix this.

**Comment by ivan-vdovin** [comment] 2022-04-29 11:48
@ThomasKientz Should be fixed, right?

**Comment by ThomasKientz** [comment] 2022-04-29 11:51
@ivan-vdovin PR https://github.com/cube-js/cube.js/pull/4314 has been merged, so it will be available in  in [next release](https://github.com/cube-js/cube.js/releases).

**Comment by guilherme-moneri** [comment] 2022-05-20 14:15
I'm having some problems with this. When using a boolean operator in the query filter, the members seem to vanish from the query parameter passed on the **/load** and **/dry-run** requests and I get the error `"Invalid query format: child \"filters\" fails because [\"filters\" at position 0 does not match any of the allowed types]"`.

This is the filter I'm using:
`[
            {
              and: [
                {
                  member: "AffiliatesPrograms.programsId",
                  operator: "equals",
                  values: [
                    this.partnerId
                  ]
                }
              ]
            }
          ]`

And the request comes out like this:
`GET https://{query-server-url}/load?query={"measures":["Affiliates.count"],"filters":[{"and":[{"operator":"equals","values":["PR714117"]}]}],"limit":10000,"order":{}}&queryType=multi`

Am I missing some addition to the schema? Both backend and frontend are using version 0.29.54 of cube.

**Comment by ThomasKientz** [comment] 2022-05-20 14:25
@guilherme-moneri You are not missing something. My guess is that `AffiliatesPrograms.programsId` doesn't exist (look for a typo maybe?).

**Comment by guilherme-moneri** [comment] 2022-05-20 14:46
@ThomasKientz If I don't use the **and** operator it works as intended though. Like this
`filters: [
            {
              member: "AffiliatesPrograms.programsId",
              operator: "equals",
              values: [
                this.partnerId
              ]
            }
          ]`

**Comment by ivan-vdovin** [comment] 2022-05-27 14:06
Hi @guilherme-moneri !
Could you open a new issue? Please make sure to attach your schema files and your query.

**Closed by ivan-vdovin** 2022-05-27 14:06 UTC
Labels: question
