### ISSUE TITLE
TimeoutError: ResourceRequest timed out

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube.js#2574] opened 2021-04-18 10:53 UTC
**Describe the bug**

official doc has described this  problem. but  if cube.js response with TimeoutError: ResourceRequest timed out. then every  request will be this.  other cube.js request will not ok

**To Reproduce**
with load test tools  and config cache with redis 

**Version:**
0.26.99

**Comment by hassankhan** [comment] 2021-04-18 13:26
Hi @rongfengliang :wave:

Thanks for posting the issue; I was wondering if you had a Docker Compose stack that we could use? It would make it really easy for us to replicate the issue 😄

**Comment by rongfengliang** [comment] 2021-04-18 14:04
@hassankhan  https://github.com/rongfengliang/graalvm-cubejs-demo/tree/ab-test  simple test (all-in-one)

**Comment by ovr** [comment] 2021-04-18 22:23
I can reproduce it. I am weird to see that Cube.js broken internally in polling connections and returns this error forever.
I will dig into it to understand the main problem of it.

**Comment by rongfengliang** [comment] 2021-04-19 04:55
@ovr  maybe  cause  by this 

RedisPool.ts (constructor)
```code
if (max > 0) {
      const destroy = options.destroyClient || (async (client) => client.end(true));

      this.pool = genericPool.createPool<AsyncRedisClient>({ create, destroy }, opts);

      this.pool.on('factoryCreateError', (error) => {
        this.poolErrors++;
      //   if more resource was request to create and   poolErrors reach  MAX_ALLOWED_POOL_ERRORS,then will always reject 
       and will TimeoutError: ResourceRequest timed out. one way was remove this code 
        // prevent the infinite loop when pool creation fails too many times
        if (this.poolErrors > MAX_ALLOWED_POOL_ERRORS) {
          // @ts-ignore
          // eslint-disable-next-line
          this.pool._waitingClientsQueue.dequeue().reject(error);
        }
      });
    }
```

**Comment by rongfengliang** [comment] 2021-04-19 05:28
remove error number check this  issue still exisis ....

**Comment by rongfengliang** [comment] 2021-04-19 09:00
add validate  function for redispool maybe better

**Comment by ovr** [comment] 2021-04-20 14:17
Fix merged & released. I am going to close this issue, because the original issue resolved.

**Closed by ovr** 2021-04-20 14:17 UTC
Labels: bug
