### ISSUE TITLE
Moving from moment to dayjs in @cubejs-client/core?

### ISSUE THREAD

**Issue by sonu247** [cube-js/cube.js#2512] opened 2021-04-08 10:13 UTC
Currently, the size of the library is too big 459kb. Adding CubeJS, to a simple, single section of the application, can exceed the size of the build.

![image](https://user-images.githubusercontent.com/33275626/114008504-eed2e800-987f-11eb-8a0b-09ad413aa64a.png)

While digging into the size, I find, it uses moment for the time calculations, and the moment itself is a big library.

![image](https://user-images.githubusercontent.com/33275626/114009449-c697b900-9880-11eb-9924-915a9094246d.png)

IDK, to what extend the moment is used in the application, but I was using moment in my application, and it was increasing the size of my main bundle and I decided to go with the [dayjs](https://www.npmjs.com/package/dayjs) instead, and it drastically optimized the main bundle. 

Maybe migrating to [dayjs](https://www.npmjs.com/package/dayjs) worth?

**Comment by vasilev-alex** [comment] 2021-04-08 16:41
Hi @sonu247! There's an open issue for that. Please see

Duplicate of #960

**Closed by vasilev-alex** 2021-04-08 16:41 UTC
