### ISSUE TITLE
401 Status code for authentication 

### ISSUE THREAD

**Issue by varun27896** [cube-js/cube.js#4384] opened 2022-04-14 16:11 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I make a request with a stale token to any of the cubejs endpoints, the response is returned only as a message stating the following {'error' : 'Request failed with status code 401'}. This makes the error handling on the client side hard since I am required to check for the message vs having to check the status code. If it were to even return a status code for such errors, all I get is a 500 from cubejs, which is not helpful at all while trying to debug.
**Describe the solution you'd like**
Would be really helpful if 401 status code is implemented as part of the other status codes defined here https://cube.dev/docs/rest-api#prerequisites-error-handling
**Describe alternatives you've considered**

**Additional context**

**Comment by ivan-vdovin** [comment] 2022-04-22 15:25
Hi @varun27896 !
It seems to be a duplicate of this one: [#833](https://github.com/cube-js/cube.js/issues/833)

**Closed** 2022-04-29 10:45 UTC
