### ISSUE TITLE
Add functionality to use other S3 vendors than AWS and GCP

### ISSUE THREAD

**Issue by olejeglejeg** [cube-js/cube.js#3204] opened 2021-08-06 06:45 UTC
**Is your feature request related to a problem? Please describe.**
We are hosted on another cloud vendor that has S3 contract compatible with AWS S3. But since currently can't override S3 endpoint, we can't use cube-store in a cloud storage mode.

**Describe the solution you'd like**
The way that would solve our problems at this stage is to add the ability to assign the S3 endpoint URL in the configuration. But in the future, we hope that it will be possible to specify any S3 storage from any vendor to work with the cube store.

**Comment by hassankhan** [comment] 2021-08-09 22:54
Duplicate of https://github.com/cube-js/cube.js/issues/2642

**Closed by hassankhan** 2021-08-09 22:54 UTC
Labels: enhancement, backend:cube-store
