### ISSUE TITLE
PreAggregations originalSql doesn't works with external preaggregation when autentication used

### ISSUE THREAD

**Issue by norbertbede** [cube-js/cube.js#1347] opened 2020-11-10 17:21 UTC
**Describe the bug**
PreAggregations: main type: `originalSql` doesn't work with external: true flag, authentication used.

SETUP
We have 2 pg RDS servers read-only replica/regular access for preaggregation. The idea is to Read data from replica DB - based on [feature external preaggregation](https://cube.dev/docs/pre-aggregations#read-only-data-source-pre-aggregations)  At the starting point, our approx 20 schema files migrated from v. 19x. to 23.x. Because we switched from logical replica to physical replica (RDS readonly replica) then we first change our schema. There is some schema where the main originalSql pre-aggregation configured. 

When we:

1. when we run query in above setup, then we getting `{ "error": "Error: relation \"ad_client\" does not exist"}` BUG
2. when I switch setup to 2x read/write db, and setup external: false, the query works.
3. when I remove originalSql pre-aggregation from the schema, then query works.
4. when I change originalSql to rollup the problem doesn't happen. Looks Implemented

**To Reproduce**
1. Set up 2 DB servers 2 users Postgres. RDS Regulate/replica
2. make the connection for source data to the replica
3. make connection to pre-aggregation db trough [externalDriverFactory](https://cube.dev/docs/pre-aggregations#read-only-data-source-pre-aggregations)
4. create a schema with originalSQL, join, UserContext filter to auth jwt payload.
5. run query by eg. postman 

**Expected behavior**
We assume allow use originalSql with external preagggration should work. Reading data from Read replica and write to regular  pg db.

**Screenshots**

**Version:**
v0.23.10

**Additional context**

Testing Setup
Instance 1. Source: RDS Postgres Read Replica 
Instance 2. Destination for Pre-Aggregation Server: RDS  Postgres
cubejs: localhost port 4000 version - latest

**ssh tunel - for source server** 
++++++++++++++++++++++
CUBEJS_DB_HOST=192.168.130.3
CUBEJS_DB_PORT=5432
CUBEJS_DB_NAME=readonly_source_db
CUBEJS_DB_USER=name
CUBEJS_DB_PASS=pw
CUBEJS_DB_TYPE=postgres
CUBEJS_API_SECRET=xxxx
NODE_ENV=development

**index.js**
  driverFactory: () => new PostgresDriver({
    readOnly: true
  }),
  externalDbType: ‘postgres’,
externalDriverFactory: () => new PostgresDriver({
  host: ‘localhost’,
  database: ‘cubejs_pre_aggregation’,
  user: ‘sssss’,
  password: ‘weqeqeqeqweqwe’,
  port: 5435

}),

EXAMPLE SCHEMA
[example-extpreaggregtion-originalSQL.txt](https://github.com/cube-js/cube.js/files/5519042/example-extpreaggregtion-originalSQL.txt)

**Comment by paveltiunov** [comment] 2020-11-10 20:25
@norbertbede Thanks for posting this! Would you mind to post `CUBEJS_LOG_LEVEL=trace` logs?

**Comment by norbertbede** [comment] 2020-11-10 20:57
@paveltiunov  the tracelog is attached.

[1347tracelog.txt](https://github.com/cube-js/cube.js/files/5520126/1347tracelog.txt)

**Comment by paveltiunov** [comment] 2020-11-12 19:20
@norbertbede I see. Could you please share your schema also?

**Comment by norbertbede** [comment] 2020-11-12 19:30
above. https://github.com/cube-js/cube.js/files/5519042/example-extpreaggregtion-originalSQL.txt

**Comment by paveltiunov** [comment] 2020-11-19 19:14
@norbertbede We'd need to provide the correct error message here. The problem is you're trying to join external `originalSql` pre-aggregation to the raw data in the main data source.

**Comment by norbertbede** [comment] 2020-11-23 18:52
@paveltiunov so this is bug should fixed hope soon. 
do you mean no need to setup workarond - wait for bugfix ?
norbert

**Comment by paveltiunov** [comment] 2020-11-25 19:47
This is actually a duplicate of #1181.

**Closed by paveltiunov** 2020-11-25 19:47 UTC
Labels: bug
