### ISSUE TITLE
vue-query-builder demo broken

### ISSUE THREAD

**Issue by ThomasKientz** [cube-js/cube.js#2448] opened 2021-03-26 20:39 UTC
The deployed demo (https://vue-query-builder-demo.cube.dev) in https://github.com/cube-js/cube.js/tree/master/examples/vue-query-builder looks broken, isn't it ?

**Comment by vasilev-alex** [comment] 2021-03-27 12:18
Duplicate of #2434

**Closed by vasilev-alex** 2021-03-27 12:18 UTC
