### ISSUE TITLE
is there a way to provide cube schema declaration types / jsdocs hints?

### ISSUE THREAD

**Issue by rawpixel-vincent** [cube-js/cube.js#3236] opened 2021-08-12 03:34 UTC
**Problem**

When creating a cube I constantly have to jump into the documentation to check if the keys are correctly named, options are what I remember.
Is there a way to type the cube function so the IDE can show hint on the available keys / options?

example:
```
const {cube} = require('...');

cube('mySchema', {...});
```

or 

```
/** @type {import('@cube...').CubeSchema} */
cube('myschema', {...});
```

best,

**Comment by paveltiunov** [comment] 2021-08-17 02:48
I guess it's a duplicate of #307.

**Closed by paveltiunov** 2021-08-17 02:48 UTC
Labels: question

**Comment by strazto** [comment] 2023-08-29 05:54
it's not a duplicate of #307 , it's asking for jsdoc type hints for schemas, not anything more complicated, just helps with IDE etc

**Comment by strazto** [comment] 2023-08-31 07:48
Hi there.
I've found a solution - 

As far as I know, there's no official typescript typings for cube schema objects (since the files are a weird transpiled js), so I rolled my own

`root/schema-types.ts`

```ts
// root/schema-types.ts

// TODO: All sql fields can also be a function
type SqlField = string;

type CommonMetadataFields = {
    // otherwise given by key name
    name?: string;
    description?: string;
    meta?: any;
    title?: string;
};

type CommonFunctionalFields = {
    public?: boolean;
    sql: SqlField;
};

type MeasureType =
    | "string"
    | "time"
    | "boolean"
    | "number"
    | "count"
    | "count_distinct"
    | "count_distinct_approx"
    | "sum"
    | "avg"
    | "min"
    | "max";

type MeasureFormat = "percent" | "currency";

type DimensionType = "time" | "string" | "number" | "boolean" | "geo";

type DimensionFormat = "image_url" | "id" | "link" | "currency" | "percent";

type Relationship =
    | "one_to_one"
    | "has_one"
    | "hasOne"
    | "one_to_many"
    | "has_many"
    | "hasMany"
    | "many_to_one"
    | "belongs_to"
    | "belongsTo";

export type CubeSchemaDefinition = {
    description: string;
    sql: SqlField;
    joins: Record<
        string,
        {
            name?: string;
            relationship: Relationship;
            sql: SqlField;
        }
    >;
    measures: Record<
        string,
        CommonMetadataFields &
            CommonFunctionalFields & {
                drill_members?: [any];
                filters?: [{ sql: SqlField }];
                format?: MeasureFormat;
                rolling_window?: {
                    leading?: string;
                    trailing?: string;
                };
                type: MeasureType;
            }
    >;
    dimensions: Record<
        string,
        CommonMetadataFields &
            CommonFunctionalFields & {
                case?: {
                    when: [
                        { sql: SqlField; label: string | { sql: SqlField } },
                    ];
                    else: { label: string };
                };
                format?: DimensionFormat;
                primaryKey?: boolean;
                propagate_filters_to_sub_query?: boolean;
                sub_query?: boolean;
                type: DimensionType;
            }
    >;
    segments: Record<string, CommonFunctionalFields & { name?: string }>;
    // TODO: refine
    preAggregations: any;
};
```

Now, in your cube schemas

`root/schemas/MySchema.js`
```js
// root/schemas/MySchema.js

cube('MySchema', 
       /** @type {import('../schema-types').CubeSchemaDefinition} */ ({
       ...
       }),
);
```

You can cast the second argument of `cube()` to `CubeSchemaDefinition`. 

**TAKE NOTE** per the [typescript via jsdoc documentation](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#casts) 

> ... This lets you cast types to other types by adding a `@type` tag before any **parenthesized** expression.

You need to wrap the schema definition object in parentheses `()` in order for the cast to work.

As in: 
```js
/** @type {import('../schema-types').CubeSchemaDefinition} */  ({ // notice the leading '('

 }) // notice the trailing ')'
```
