### ISSUE TITLE
preAggregation.refreshKey not respected during runScheduledRefresh in multi-tenancy setup 

### ISSUE THREAD

**Issue by SamShiSS** [cube-js/cube.js#678] opened 2020-05-29 19:54 UTC
**Describe the bug**
see title.
the preAggregation tables are refreshed at every `runScheduledRefresh()` call regardless of whether its `refreshKey` has changed or not

**To Reproduce**
1. set up a multi-tenancy cubejs server, with a single database for all tenants, and one Postgres schema per tenant:
```
    const server = new CubejsServer({
        contextToAppId: ({ authInfo } =>
            `CUBEJS_ACCOUNT_${authInfo.accountId}`,
        contextToDataSourceId: () => 'common-connection-pool',
        preAggregationsSchema: ({ authInfo } =>
           `acc_${authInfo.accountId}_preagg`,
    });
```
2. Create a cube with preAggregation of `rollup` type. Add some values to `preAggregation.measureReferences` and `preAggregation.dimensionReferences`
3. set `preAggregation.scheduledRefresh` to `true` and `preAggregation.refreshKey` to `{ every: '10 minutes'}`
4. set up `runScheduledRefresh` to execute every 60 seconds for each account 
```
setInterval(async () => {
    for (const account in accounts) {
        await server.runScheduledRefresh({ authInfo: { accountId: account.id }})
    }
}, 60000)

 ````` 
5. set `CUBEJS_CACHE_AND_QUEUE_DRIVER=memory` in .env. 
6. start the server, then query the cube once every 60 seconds, observe the `lastRefreshTime` value in response. The `lastRefreshTime` updates every 60 seconds

**Expected behavior**
The cube's preAggregation tables only refreshed when the result of `refreshKey` query has changed (every 10 minutes in this case)

**Version:**
@cubejs-backend/server: 0.19.18
@cubejs-backend/postgres-driver: 0.19.17,
postgres: 12

**Note**
1. This issue does not appear when there is only a single tenant
2. Not sure if this issue would still appear when redis is used
3. I have also observed that using preAggregation tables slow down query performance as opposed to speeding it up

**Comment by paveltiunov** [comment] 2020-05-30 08:05
@SamShiSS Hey Sam! Could you please share data schema?

**Comment by SamShiSS** [comment] 2020-05-30 16:47
@paveltiunov here is schema of the cube of concern
```
const { authInfo } = COMPILE_CONTEXT;

cube(`SurveyResponses`, {
    sql: `SELECT * FROM acc_${authInfo.accountId}.survey_responses`,

    joins: {
        BooleanResponsesOverall: {
            sql: `${CUBE}.response_id = ${BooleanResponsesOverall}.response_id`,
            relationship: `hasOne`,
        },

        Channels: {
            sql: `${CUBE}.channel_id = ${Channels}.id`,
            relationship: `belongsTo`,
        },

        Locations: {
            sql: `${CUBE}.location_id = ${Locations}.id`,
            relationship: `belongsTo`,
        },

        LocationAncestors: {
            sql: `${CUBE}.location_id = ${LocationAncestors}.location_id`,
            relationship: `hasMany`,
        },

        Surveys: {
            sql: `${CUBE}.survey_id = ${Surveys}.id`,
            relationship: `belongsTo`,
        },
    },

    measures: {
        count: {
            type: `count`,
            drillMembers: [id, date, Locations.title, Channels.title],
        },
    },

    dimensions: {
        id: {
            sql: `response_id`,
            type: `string`,
            primaryKey: true,
        },

        date: {
            sql: `date`,
            type: `time`,
        },
    },

    refreshKey: {
        sql: `SELECT COUNT(*) FROM acc_${authInfo.accountId}.survey_responses`,
    },

    preAggregations: {
        main: {
            type: `rollup`,
            measureReferences: [
                'SurveyResponses.count',
                'BooleanResponsesOverall.count',
                'BooleanResponsesOverall.positive',
                'BooleanResponsesOverall.negative',
                'BooleanResponsesOverall.percentPositive',
            ],
            dimensionReferences: [
                Channels.title,
                Channels.type,
                Locations.title,
                Locations.timezone,
                Surveys.title,
                LocalTime.localHour,
            ],
            timeDimensionReference: date,
            granularity: 'day',
            partitionGranularity: 'week',
            scheduledRefresh: true,
            refreshKey: {
                every: `10 minutes`,
            },
        },
    },
});
```

**Comment by paveltiunov** [comment] 2020-05-30 21:32
@SamShiSS Could you please share your query also? It seems it just doesn't hit rollup. Could you please check if playground tells you this exact rollup matched?

**Comment by SamShiSS** [comment] 2020-05-30 21:55
@paveltiunov This is my query, which is sending to this cube that uses pre-aggregation:
```
query: {"measures":["SurveyResponses.count"],"timeDimensions":[{"dimension":"SurveyResponses.date","granularity":"day","dateRange":"This month"}],
```
And this is the response of the query:
<img width="701" alt="Screen Shot 2020-05-30 at 5 53 01 PM" src="https://user-images.githubusercontent.com/26658559/83339691-6a4a2d00-a29e-11ea-9f65-874f56a629bd.png">
It appears to be using the pre-aggregation tables, but taking longer than without using pre-aggregation. Also, the `refreshKey` of the cube appears to not be respected based on the `lastRefreshTime` and the server logs

**Comment by cd-romulus** [comment] 2020-06-15 11:42
@paveltiunov, @SamShiSS I can reproduce this behavior even for normal user queries that use preAggregations. It seems like building the pre-aggregation  of one tenant invalidates the pre-aggregation of all other tenants. As long as we issue the query for just one tenant, however, the refresh key seems to be respected

**Comment by paveltiunov** [comment] 2020-06-17 05:56
@cd-romulus Could you please share your multitenancy setup?

**Comment by cd-romulus** [comment] 2020-06-17 12:50
@paveltiunov here is a minimalistic version of our setup that reproduces the problem:

- Create a test cube:

```js
cube(`MyCube`, {
    //sql: `SELECT '${schema}' as schem, '${prefix}' as prefix, now() as ts from ${schema}.${prefix}mytable, pg_sleep(10)`, // most reliable
    sql: `SELECT '${schema}' as schem, '${prefix}' as prefix, now() as ts from pg_sleep(10)`,
    //sql: `SELECT 'public' as schem, '' as prefix, now() as ts from mytable, pg_sleep(10)`, // this has the same problem but for whatever reason it is less reliable to reproduce

    measures:{
        one:{
            sql: `1`,
            type: 'number'
        }
    },
    dimensions:{
        schem:{
            sql: 'schem',
            type: 'string'
        },
        pref:{
            sql: 'prefix',
            type: 'string'
        },
        timestamp:{
            sql: 'ts',
            type: 'time'
        }
    },
    preAggregations:{
        test: {
            type: 'rollup',
            dimensionReferences: [schem,pref],
            measureReferences: [one],
            timeDimensionReference: timestamp,
            granularity: 'day',
            partitionGranularity: 'month',
            refreshKey:{
                every: `1 day`,
                incremental: true,
                updateWindow: `2 day`
            },
        }
    }
})
```

- start the cubejs server with these settings:
```js
const cubeJsServer = new CubejsServer({
        basePath: '/:tenantId/cubejs-api',
        checkAuthMiddleware: (req,res, next) => {req.authInfo={tenantId: req.params.tenantId, u: {schema: 'tenant'+req.params.tenantId, prefix:''}}; if (next) {next();}}, //dummy middleware just to populate the authInfo field DO NOT USE IN PRODUCTION
        contextToAppId: ({authInfo}) => `CUBEJS_APP_ID_${authInfo.tenantId}`, //Identifier under which all caching is done. The function is passed the express req object but only uses the authInfo field. This is called for every request
        contextToDataSourceId: ({authInfo}) => 'CUBEJS_DATASOURCE_ID_test', // currently all tenants use the same datasource
        preAggregationsSchema: ({ authInfo }) => `${authInfo.u.schema}_${authInfo.u.prefix}pre_aggregations`, //use per tenant schema for preaggregations
        driverFactory: (context) => new PostgresDriver({host:'localhost', port: 5432, database: 'test', user: 'postgres', password: ''}), //hard code test connection for all tenants
        allowUngroupedWithoutPrimaryKey: true,
    });
    const {port, tlsPort, server, app} = await cubeJsServer.listen().catch(e => {
            console.error('Fatal error during server start: ');
            console.error(e.stack || e);
            })
```

- request this query for tenant1 until a result is returned (from `http://localhost:4000/1/cubejs-api/v1/load`)

```json
{
  "dimensions": ["MyCube.schem","MyCube.pref"
  ],
  "measures": [
    "MyCube.one"
  ],
  "timeDimensions": [
    {
      "dimension": "MyCube.timestamp",
      "dateRange": "This month","granularity":"day"
    }
  ],
"timezone":"Europe/Berlin",
"renewQuery":true
}
```

- request the same query for tenant2 until a result is returned (from `http://localhost:4000/2/cubejs-api/v1/load`)

-  now request the same query again for tenant1 (from `http://localhost:4000/1/cubejs-api/v1/load`)

You should see that the pre-aggregation is rebuilt.

(For some reason, it seems that the issue is more reliably reproduced, if tenant1.mytable and tenant2.mytable are part of the query (and exist of course).)

I tried this on
@cubejs-backend/postgres-driver: 0.19.20,
@cubejs-backend/server: 0.19.33,
Postgres: 11 & 12

**Comment by paveltiunov** [comment] 2022-07-04 23:08
Should be fixed in the latest version.

**Closed by paveltiunov** 2022-07-04 23:08 UTC
Labels: question, backend:server
