### ISSUE TITLE
Dynamic schema with joins

### ISSUE THREAD

**Issue by LeeJiaLe** [cube-js/cube.js#2562] opened 2021-04-14 23:40 UTC
I have a dynamic schema which load like this:

```
const fetch = require('node-fetch');

import {
  transformDimensions,
  transformMeasures,
  transformJoins
} from './utils';

import {
  url
} from '../environment'
asyncModule(async () => {
  const dynamicCubes = await (
    await fetch(url())
  ).json();
  // {
  //   "bill": {
  //     "sql": "SELECT * FROM public.\"bill\"",
  //       "dataSource": "default",
  //         "joins": {
  //       "items": {
  //         "relationship": "belongsTo",
  //           "sql": "\"items\".__fk = \"bill\".__id"
  //       }
  //     },
  //     "measures": {
  //       "count": {
  //         "sql": "COUNT(DISTINCT \"bill\".__id)",
  //           "type": "number"
  //       }
  //     },
  //     "dimensions": {
  //       "__id": {
  //         "sql": "__id",
  //           "type": "string",
  //             "primaryKey": true
  //       },
  //       "status": {
  //         "sql": "\"bill\".\"status\"",
  //           "type": "string"
  //       }
  //     }
  //   },
  //   "items": {
  //     "sql": "SELECT * FROM public.\"items\"",
  //       "dataSource": "default",
  //         "joins": { },
  //     "measures": {
  //       "count": {
  //         "sql": "COUNT(DISTINCT \"items\".__id)",
  //           "type": "number"
  //       },
  //       "quantity": {
  //         "sql": "\"items\".\"quantity\"",
  //           "type": "sum"
  //       }
  //     },
  //     "dimensions": {
  //       "__id": {
  //         "sql": "__id",
  //           "type": "string",
  //             "primaryKey": true
  //       },
  //       "status": {
  //         "sql": "\"items\".\"status\"",
  //           "type": "string"
  //       }
  //     }
  //   }
  // }
  for (const key in dynamicCubes) {
    if (Object.hasOwnProperty.call(dynamicCubes, key)) {
      const element = dynamicCubes[key];
      const dimensions = transformDimensions(element.dimensions);
      const measures = transformMeasures(element.measures);
      const joins = transformJoins(element.joins);

      cube(key, {
        sql: element.sql,
        joins,
        dimensions,
        measures
      })
    }
  }
})
```

all the function are reference to the https://cube.dev/docs/schema/dynamic-schema-creation
the transformJoin is like this:
```
export const transformJoins = (joins) => {
  return Object.keys(joins).reduce((result, joinName) => {
    const joinDefinition = joins[joinName];

    return {
      ...result,
      [joinName]: convertStringPropToFunction(
        ['sql'],
        joinDefinition
      ),
    };
  }, {});
};
```

But it throw error:
`Error: Error: invalid reference to FROM-clause entry for table "items"`

while I query:
`{"measures":["items.quantity"],"timeDimensions":[],"order":{"items.quantity":"desc"},"dimensions":["bill.status"]}`

the error sql is looks like this:
```
SELECT
  q_0."bill__status",
  "items__quantity" "items__quantity"
FROM
  (
    SELECT
      "keys"."bill__status",
      sum("items"."quantity") "items__quantity"
    FROM
      (
        SELECT
          DISTINCT "bill"."status" "bill__status",
          "items_key__items".__id "items____id"
        FROM
          public."bill" AS "items_key__bill"
          LEFT JOIN public."items" AS "items_key__items" ON "items".__fk = "bill".__id
      ) AS "keys"
      LEFT JOIN public."items" AS "items_key__items" ON "keys"."items____id" = "items_key__items".__id
    GROUP BY
      1
  ) as q_0
ORDER BY
  2 DESC
LIMIT
  10000
```

after that I try to define the cube schema manually and change table name to variable like this:
```
cube(`bill`, {
  sql: `SELECT * FROM public."bill"`,
  dataSource: 'default',
  joins: {
    items: {
      relationship: 'belongsTo',
      sql: `${items}.__fk = ${bill}.__id`,
    },
  },
  measures: {
    count: {
      sql: `COUNT(DISTINCT ${bill}.__id)`,
      type: 'number',
    },
  },
  dimensions: {
    __id: {
      sql: '__id',
      type: 'string',
      primaryKey: true,
    },
    status: {
      sql: `${bill}."status"`,
      type: 'string',
    },
  },
});

cube('items', {
  sql: 'SELECT * FROM public."items"',
  dataSource: 'default',
  joins: {},
  measures: {
    count: {
      sql: `COUNT(DISTINCT ${items}.__id)`,
      type: 'number',
    },
    quantity: {
      sql: `${items}."quantity"`,
      type: 'sum',
    },
  },
  dimensions: {
    __id: {
      sql: `${items}.__id`,
      type: 'string',
      primaryKey: true,
    },
    status: {
      sql: `${items}."status"`,
      type: 'string',
    },
  },
});
```

the result work fine and generated correct sql:
```
SELECT
  q_0."bill__status",
  "items__quantity" "items__quantity"
FROM
  (
    SELECT
      "keys"."bill__status",
      sum("items_key__items"."quantity") "items__quantity"
    FROM
      (
        SELECT
          DISTINCT "items_key__bill"."status" "bill__status",
          "items_key__items".__id "items____id"
        FROM
          public."bill" AS "items_key__bill"
          LEFT JOIN public."items" AS "items_key__items" ON "items_key__items".__fk = "items_key__bill".__id
      ) AS "keys"
      LEFT JOIN public."items" AS "items_key__items" ON "keys"."items____id" = "items_key__items".__id
    GROUP BY
      1
  ) as q_0
ORDER BY
  2 DESC
LIMIT
  10000
```

may I know how can dynamic schema achieve the same result here? or I can only create the schema manually?

**Comment by vasilev-alex** [comment] 2021-04-15 09:07
Duplicate of #1880

**Comment by hassankhan** [comment] 2021-04-15 14:09
@rongfengliang also posted a [workaround in the same issue](https://github.com/cube-js/cube.js/issues/1880#issuecomment-820421455).

**Closed** 2021-04-16 05:58 UTC
Labels: duplicate

**Comment by DrewHoo** [comment] 2021-04-17 17:16
@vasilev-alex are you sure this is a duplicate of #1880? this is about joining a dynamic schema to a dynamic schema, whereas #1880 is about joining a dynamic schema to a static one. For instance, @rongfengliang’s workaround for this issue does not work for me.

**Comment by emahuni** [comment] 2022-05-12 15:47
I've this exact problem, exactly! It seems like documentation is lacking this example. It'd be great if someone can add a dynamic schema generation for joins as well. The problem seem to come from the fact that we can't refer to Cubes here someone as we do statically.

**Comment by jozefbalun** [comment] 2023-02-23 12:48
I have same problem, have you any workaround for this dynamic schema generation for joins ?

**Comment by emahuni** [comment] 2023-02-27 05:32
> I have same problem, have you any workaround for this dynamic schema generation for joins ?

My solution was to actually write the generated schema to files as if they're static and it worked well. I had to write a translator of my models to automatically do this during the development env only. Since the models don't change every time or  in production, I don't need to do it every time. Cube uses the schema as if it's manually written.

**Comment by danieljaniga** [comment] 2023-02-27 19:35
I have exact same problem, generated aliases isn’t referenced correctly. @paveltiunov can you help with this? Thanks

**Comment by igorlukanin** [comment] 2024-10-09 13:43
@DrewHoo @emahuni @jozefbalun @danieljaniga Could you please take a look at this message? I has a working code example: https://github.com/cube-js/cube/issues/1880#issuecomment-2402247001

**Comment by igorlukanin** [comment] 2024-10-09 13:46
That being said, I do think that the issue reported here is a duplicate of another issue: https://github.com/cube-js/cube/issues/8495

I was able to reproduce it with the following data model:

```js
// model/utils.js
export const convertStringPropToFunction = (propNames, dimensionDefinition) => {
  let newResult = { ...dimensionDefinition };
  propNames.forEach((propName) => {
    const propValue = newResult[propName];
 
    if (!propValue) {
      return;
    }
 
    newResult[propName] = () => propValue;
  });
  return newResult;
};
 
export const transformDimensions = (dimensions) => {
  return Object.keys(dimensions).reduce((result, dimensionName) => {
    const dimensionDefinition = dimensions[dimensionName];
    return {
      ...result,
      [dimensionName]: convertStringPropToFunction(
        ["sql"],
        dimensionDefinition
      ),
    };
  }, {});
};
 
export const transformMeasures = (measures) => {
  return Object.keys(measures).reduce((result, dimensionName) => {
    const dimensionDefinition = measures[dimensionName];
    return {
      ...result,
      [dimensionName]: convertStringPropToFunction(
        ["sql", "drill_members"],
        dimensionDefinition
      ),
    };
  }, {});
};

export const transformJoins = (joins) => {
  return Object.keys(joins).reduce((result, joinName) => {
    const joinDefinition = joins[joinName];

    return {
      ...result,
      [joinName]: convertStringPropToFunction(
        ['sql'],
        joinDefinition
      ),
    };
  }, {});
};

const dynamicCubes = {
    "bill": {
      "sql": "SELECT 'abc' AS __id, 'done' AS status",
        "dataSource": "default",
          "joins": {
        "items": {
          "relationship": "many_to_one",
            "sql": "\"items\".__fk = \"bill\".__id"
        }
      },
      "measures": {
        "count": {
          "sql": "COUNT(DISTINCT \"bill\".__id)",
            "type": "number"
        }
      },
      "dimensions": {
        "__id": {
          "sql": "__id",
            "type": "string",
              "primaryKey": true
        },
        "status": {
          "sql": "\"bill\".\"status\"",
            "type": "string"
        }
      }
    },
    "items": {
      "sql": "SELECT 'def' AS __id, 'abc' AS __fk, 'done' AS status, 123 AS quantity",
        "dataSource": "default",
          "joins": { },
      "measures": {
        "count": {
          "sql": "COUNT(DISTINCT \"items\".__id)",
            "type": "number"
        },
        "quantity": {
          "sql": "\"items\".\"quantity\"",
            "type": "sum"
        }
      },
      "dimensions": {
        "__id": {
          "sql": "__id",
            "type": "string",
              "primaryKey": true
        },
        "status": {
          "sql": "\"items\".\"status\"",
            "type": "string"
        }
      }
    }
  }

  asyncModule(async () => {
    for (const key in dynamicCubes) {
      if (Object.hasOwnProperty.call(dynamicCubes, key)) {
        const element = dynamicCubes[key];
        const dimensions = transformDimensions(element.dimensions);
        const measures = transformMeasures(element.measures);
        const joins = transformJoins(element.joins);

        cube(key, {
          sql: element.sql,
          joins,
          dimensions,
          measures
        })
      }
    }
  })
```

When the join relationship is `many_to_one`, an incorrect SQL is generated, and the following error arises: `missing FROM-clause entry for table "items"`.

<img width="1392" alt="Screenshot 2024-10-09 at 15 46 08" src="https://github.com/user-attachments/assets/ae8a4d39-dbb4-4d4f-aae3-fd29b068a2cb">

When the join relationship is `one_to_many`, a different and correct SQL is generated but it's not relevant, a correct SQL should be generated in any case.
