### ISSUE TITLE
Integer to bigint generic type conversion for bigquery

### ISSUE THREAD

**Issue by mrbirkov** [cube-js/cube.js#600] opened 2020-04-19 04:16 UTC
I am using Bigquery datasource and pre-aggregation database using MySQL & Postgresql

When querying cubejs for pre-aggregation exporting to mysql I got the following error.

> Error: Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'orders_pre_agg__total_price' at row 40

Using postgresql as the pre-aggregation database  also gives similar error below.

> Error: Error: value "4361112608" is out of range for type integer

Since the maximum value of the mysql db for integer type is  "2147483647" we need to add integer -> bigint generic type conversion for bigquery so when inserted to mysql/postgresql it will use bigint type. 

Seems that  the default integer type in bigquery is INT64 so the preaggregation works in the source database.

**Expected behavior**
Cubejs should create / update the pre-aggregation table in mysql /postgresql.

We'd need to add integer -> bigint generic type conversion for big query.

**Version:**
0.18.4

**Comment by paveltiunov** [comment] 2020-04-20 04:32
@mrbirkov Thanks for posting this! Need to fix in `BigQueryDriver`.

**Comment by hassankhan** [comment] 2021-04-26 15:32
Closing as duplicate of https://github.com/cube-js/cube.js/issues/1233

**Closed by hassankhan** 2021-04-26 15:32 UTC
Labels: bug, driver:bigquery, help wanted
