### ISSUE TITLE
Ability to Define OR filter in JSON Query

### ISSUE THREAD

**Issue by emahuni** [cube-js/cube.js#806] opened 2020-07-08 02:48 UTC
**Is your feature request related to a problem? Please describe.**
 I want a way to filter using either of the given filter params instead of every filter. The problem is every param in filters array is used as **AND** and there is no way, as far as I have seen, to tell it to **OR** it.

 eg: A Database has a table of records with **to** and **from** numbers for calls  _made_ **or** _received_  in each row. Each record may look like this:
```js
{
  id: 32,
 call_sid: 1dfe,
 to_number: 400,
 from_number: 100
}
```
I want to get calls that were done **OR** received by a specific number in 1 query. So the following will not work since it will try to find calls _to_  **AND** _by_ the same number:
```js
"filters": [
    {
      "dimension": "To.number",
      "operator": "equals",
      "values": [
        "100"
      ]
    },
    {
      "dimension": "From.number",
      "operator": "equals",
      "values": [
        "100"
      ]
    }
  ],
```
Which is to say `To.number` **AND** `From.number` should be equal to _100_.

**Describe the solution you'd like**
What I want is to be able to just do the exact same kind of query only specifying that this is an **OR** filter and not **AND**. I want a way to say either `To.number` **OR** `From.number` should be equal to _100_. 

**Describe alternatives you've considered**
If only Cube could just treat any arrayed filter as an OR filter then it'd be easier and more powerful to use, eg:
```js
"filters": [
   [ // notice this addition here
      {
        "dimension": "To.number",
        "operator": "equals",
        "values": [
          "100"
        ]
      },
      {
        "dimension": "From.number",
        "operator": "equals",
        "values": [
          "100"
        ]
      }
    ] // and here
  ],
```
Notice the added `[ ]` that encapsulates both filters. This is a way of grouping them as a single **OR** filter. This can be any number of filters that the user can group.

So this will mean that either `To.number` **OR** `From.number` should be equal to _100_.

**Comment by vasilev-alex** [comment] 2020-07-08 07:54
Duplicate of #259

**Comment by emahuni** [comment] 2020-07-08 08:05
Yes looks the same, but this isn't as complex and breaking as #259. I thought of the same way but didn't want it to be breaking. That's why I said exact same kind of query... So here is just addition of array interpretation. Which should work the exact same way in all code then put an OR in the final DB code where there's supposed to be an AND.

**Comment by paveltiunov** [comment] 2020-07-08 19:59
@emahuni Hey Emmanuel! Thanks for posting this one! #259 is already on our roadmap so your use case will be covered as part of it.

**Closed by paveltiunov** 2020-07-08 19:59 UTC
Labels: duplicate

**Comment by emahuni** [comment] 2020-07-09 03:09
Wonderful
