### ISSUE TITLE
Filters on rollup join preaggregations do not filter out data as expected

### ISSUE THREAD

**Issue by adraks829** [cube-js/cube.js#5856] opened 2022-12-21 22:06 UTC
**Describe the bug**
Filtering against rollup join preaggregations does not match the functionality when directly querying database data with the same dimensions and filters.

**To Reproduce**
Open cube playground and execute the following scenarios:
1. Base case(no filters) Select Measures: Actions Count | Dimensions: Property Actions Property Id, Properties Label, Actions Action Type | Filters: none
Expected and actual behavior: 4 results are returned, counts by action type and property. 2 for Property 1 and action_type1, 1 for Property 2 and action_type3, and 1 each for Property 1 and 2 with action_type2, all with proper labels

2. Select Measures: Actions Count | Dimensions: Property Actions Property Id, Properties Label, Actions Action Type | Filters: Properties Label equals 'Property 3'
Expected behavior: No results are returned because Property 3 has no correlating actions
Actual behavior: All results are returned with null values for Label

3. Measures: Actions Count | Dimensions: Property Actions Property Id, Properties Label, Actions Action Type | Filters: Properties Label equals 'Property 1'
Expected behavior: Two results are returned for the counts related to Property 1 with the proper label data
Actual behavior: All results are returned, Property 1 results have the correct Label and Property 2 results have null Label

**Screenshots**
Screenshots of the results for the previous scenario are provided below:
No filters without preaggregations
![nofilter-noagg](https://user-images.githubusercontent.com/13393237/209009123-71b33d41-82c7-49d4-a40e-84ff3a32ec31.png)
Filter for Property 3 with no preaggregations
![filter-noagg](https://user-images.githubusercontent.com/13393237/209009266-4cef4fbc-da6f-4d83-b915-b383701fcc4a.png)
Filter for Property 1 with no preaggregations
![filter-noagg-results](https://user-images.githubusercontent.com/13393237/209009342-f56c676f-df5f-4778-98b3-f5210f5cf497.png)
No filters with preaggregations
![nofilter-aggregated](https://user-images.githubusercontent.com/13393237/209009443-493fd222-f566-421e-a5e9-3703dada2c3c.png)
Filter for Property 3 with preaggregations
![filter-aggregated-no-match](https://user-images.githubusercontent.com/13393237/209009537-9cc3a098-1069-46e9-a1cc-d4d6ecc1822e.png)
Filter for Property 1 with preaggregations
![filter-aggregated-partial-match](https://user-images.githubusercontent.com/13393237/209009577-61c8b24f-5ed1-4c51-83e6-7f09e4f55fc1.png)

**Minimally reproducible Cube Schema**

```javascript
cube(`Actions`, {
  sql: `SELECT '1' as action_id, getdate() as created, 'action_type1' as action_type
        UNION ALL
        SELECT '2' as action_id, getdate() as created, 'action_type1' as action_type
        UNION ALL
        SELECT '3' as action_id, getdate() as created, 'action_type2' as action_type
        UNION ALL
        SELECT '4' as action_id, getdate() as created, 'action_type2' as action_type
        UNION ALL
        SELECT '5' as action_id, getdate() as created, 'action_type3' as action_type`,
  
  measures: {
    count: {
      type: `count`
    }
  },
  dimensions: {
    action_id: {
      sql: `action_id`,
      type: `string`,
      shown: true,
      primaryKey: true
    },
    action_type: {
      sql: `action_type`,
      type: `string`
    },
    created: {
      sql: `created`,
      type: `time`
    }
  },
  joins: {
    PropertyActions: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions.action_id}`
    }
  },
  preAggregations: {
    action_count: {
      measures: [Actions.count],
      dimensions: [
        PropertyActions.property_id, 
        Actions.action_type
      ],
      indexes: {
        property1Index: {
          columns: [PropertyActions.property_id]
        }
      },
      timeDimension: Actions.created,
      granularity: `day`,
      partitionGranularity: `month`,
      refreshKey: {
        every: `1 day`,
        incremental: true,
        updateWindow: `7 day`
      }
    },
  }
});

cube(`Properties`, {
    sql: `SELECT 'id1' as property_id, 'Property 1' as label
        UNION ALL
        SELECT 'id2' as property_id, 'Property 2' as label
        UNION ALL
        SELECT 'id3' as property_id, 'Property 3' as label`,

    dimensions: {
        property_id: {
            sql: 'property_id',
            type: 'string',
            primaryKey: true,
            shown: true
        },
        label: {
            sql: 'label',
            type: 'string'
        }
    },

    preAggregations: {
        propertyRollup: {
            dimensions: [Properties.property_id,Properties.label],
            indexes: {
                propertyIndex: {
                    columns: [Properties.property_id]
                }
            }
        },
    }
});

cube('PropertyActions', {
    sql: `SELECT '1' as action_id, 'id1' as property_id
        UNION ALL
        SELECT '2' as action_id, 'id1' as property_id
        UNION ALL
        SELECT '3' as action_id, 'id1' as property_id
        UNION ALL
        SELECT '4' as action_id, 'id2' as property_id
        UNION ALL
        SELECT '5' as action_id, 'id2' as property_id`,
    
    dimensions: {
        id: {
            sql: `CONCAT(${CUBE}.property_id, ${CUBE}.action_id)`,
            type: `number`,
            primaryKey: true,
        },
        property_id: {
            sql: 'property_id',
            type: 'string',
            shown: true
        },
        action_id: {
            sql: 'action_id',
            type: 'string',
            shown: false
        },
        property_type: {
            sql: 'property_type',
            type: 'string',
            shown: false
        }
    },

    joins: {
        Properties: {
            relationship: 'hasMany',
            sql: `${PropertyActions.property_id} = ${Properties.property_id}`
        }
    },

    preAggregations: {
        propRollup: {
            type: `rollupJoin`,
            measures: [
                Actions.count
            ],
            dimensions: [
                PropertyActions.property_id,
                Properties.label,
                Actions.action_type
            ],
            rollups: [Actions.action_count, Properties.propertyRollup]
        }
    }
});

```

**Version:**
cube: [0.31.10] cubestore: [0.31.5]

**Additional context**

**Comment by paveltiunov** [comment] 2022-12-22 06:07
Duplicate of #3777. @adraks829 Could you please update Cube Store to the latest version as it was fixed?

**Closed** 2022-12-23 17:57 UTC
Labels: duplicate
