### ISSUE TITLE
Core dumped cubestore docker

### ISSUE THREAD

**Issue by aparfeno** [cube-js/cube.js#5562] opened 2022-11-04 14:12 UTC
When running cubestore docker image, receive an immediate "Illegal instruction (core dumped)"

Runtime is a Ubuntu environment running as a Linux container in Proxmox v 7.1-12:

Proxmox: 7.1-12/b3c09de3
Linux 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200)

Linux Container:
Ubuntu
Linux  5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) x86_64 x86_64 x86_64 GNU/Linux

I've tried various versions of docker available on https://hub.docker.com/r/cubejs/cubestore/tags?page=60.
The problem started with build-20 .

**Comment by paveltiunov** [comment] 2022-11-04 16:37
@aparfeno You need to use `non-avx` image tag.

**Comment by paveltiunov** [comment] 2022-11-04 16:38
Duplicate of #3336

**Closed by paveltiunov** 2022-11-04 16:38 UTC
Labels: question
